/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 17-Set.-2024 17:09:35 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Comprobante]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Comprobante]
GO

/* Create Tables */

CREATE TABLE [Comprobante]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Codigo] varchar(50) NULL,
	[Monto] decimal(18,2) NULL,
	[CodigoDetraccion] varchar(4) NULL,
	[Creado] varchar(50) NULL,
	[CreadoPor] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Comprobante] 
 ADD CONSTRAINT [PK_Comprobante]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO


select * from Comprobante


insert into Comprobante
values
('F-030303',100.00,'023',GETDATE(),'admin')


--- Obtener
CREATE PROCEDURE sp_ObtenerComprobante
AS
BEGIN
    SELECT [Id], [Codigo], [Monto], [CodigoDetraccion], [Creado], [CreadoPor]
    FROM [Comprobante]
    ORDER BY Id;
END
--- Registrar
CREATE PROCEDURE sp_RegistrarComprobante
    @Codigo VARCHAR(50),
    @Monto DECIMAL(18, 2),
    @CodigoDetraccion VARCHAR(4),
    @Creado VARCHAR(50),
    @CreadoPor VARCHAR(50),
    @Id INT OUTPUT 
AS
BEGIN
    INSERT INTO Comprobante (Codigo, Monto, CodigoDetraccion, Creado, CreadoPor)
    VALUES (@Codigo, @Monto, @CodigoDetraccion, @Creado, @CreadoPor);

    SET @Id = SCOPE_IDENTITY(); 
END
GO
-- Actualizar
CREATE PROCEDURE sp_ActualizarComprobante
    @Id INT,
    @Codigo VARCHAR(50),
    @Monto DECIMAL(18, 2),
    @CodigoDetraccion VARCHAR(4),
    @Creado VARCHAR(50),
    @CreadoPor VARCHAR(50)
AS
BEGIN
    UPDATE Comprobante
    SET Codigo = @Codigo,
        Monto = @Monto,
        CodigoDetraccion = @CodigoDetraccion,
        Creado = @Creado,
        CreadoPor = @CreadoPor
    WHERE Id = @Id;
END
GO
