
CREATE TABLE Comprobante (
    Id int NULL,
    DocumentoPago_Id int NULL,
    Nro NVARCHAR(255) NULL,
    FechaEmision DATETIME NULL,
    Moneda_Id NVARCHAR(255) NULL,
    Proveedor_NroIdentificacion NVARCHAR(255) NULL,
    Proveedor_RazonSocial NVARCHAR(255) NULL,
    Cliente_NroIdentificacion NVARCHAR(255) NULL,
    Cliente_RazonSocial NVARCHAR(255) NULL,
    SubTotal DECIMAL(18, 2) NULL,
    Anticipo DECIMAL(18, 2) NULL,
    Descuento DECIMAL(18, 2) NULL,
    OperacionGravada DECIMAL(18, 2) NULL,
    OperacionExonerada DECIMAL(18, 2) NULL,
    ISC DECIMAL(18, 2) NULL,
    IVA DECIMAL(18, 2) NULL,
    OtroCargo DECIMAL(18, 2) NULL,
    OtroTributo DECIMAL(18, 2) NULL,
    Total DECIMAL(18, 2) NULL,
    OperacionGratuita DECIMAL(18, 2) NULL,
    TotalTexto NVARCHAR(255) NULL,
    TipoDocumento NVARCHAR(255) NULL,
    OrdenCompra_Nro NVARCHAR(255) NULL,
    NotaRecepcion_Codigo NVARCHAR(255) NULL,
    Codigo_Detraccion NVARCHAR(255) NULL,
    FechaConsulta DATETIME NULL,
    DiaPago INT NULL,
    FechaVencimientoPago DATETIME NULL,
    PorcentajeDetraccion DECIMAL(18, 2) NULL,
    MontoDetraccion DECIMAL(18, 2) NULL,
    DescripcionDetraccion NVARCHAR(255) NULL,
    EstadoSunat NVARCHAR(255) NULL,
    TipoDocumentoNeoGrid NVARCHAR(255) NULL,
    MontoOtrosCargos DECIMAL(18, 2) NULL,
    CorrelativoPortal INT NULL,
    OtroCargoAplicable DECIMAL(18, 2) NULL,
    Creado DATETIME NULL,
);

