/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 17-Set.-2024 17:09:35 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Comprobante]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Comprobante]
GO

/* Create Tables */

CREATE TABLE [Comprobante]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Codigo] varchar(50) NULL,
	[Monto] decimal(18,2) NULL,
	[CodigoDetraccion] varchar(4) NULL,
	[Creado] varchar(50) NULL,
	[CreadoPor] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Comprobante] 
 ADD CONSTRAINT [PK_Comprobante]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO
