CREATE TABLE DocumentoPago (
    Id UNIQUEIDENTIFIER NULL,
    DocumentoPago_Id UNIQUEIDENTIFIER NULL,
    Nro NVARCHAR(255) NOT NULL,
    FechaEmision DATETIME NOT NULL,
    Moneda_Id NVARCHAR(255) NOT NULL,
    Proveedor_NroIdentificacion NVARCHAR(255) NOT NULL,
    Proveedor_RazonSocial NVARCHAR(255) NOT NULL,
    Cliente_NroIdentificacion NVARCHAR(255) NOT NULL,
    Cliente_RazonSocial NVARCHAR(255) NOT NULL,
    SubTotal DECIMAL(18, 2) NOT NULL,
    Anticipo DECIMAL(18, 2) NOT NULL,
    Descuento DECIMAL(18, 2) NOT NULL,
    OperacionGravada DECIMAL(18, 2) NOT NULL,
    OperacionExonerada DECIMAL(18, 2) NOT NULL,
    ISC DECIMAL(18, 2) NOT NULL,
    IVA DECIMAL(18, 2) NOT NULL,
    OtroCargo DECIMAL(18, 2) NOT NULL,
    OtroTributo DECIMAL(18, 2) NOT NULL,
    Total DECIMAL(18, 2) NOT NULL,
    OperacionGratuita DECIMAL(18, 2) NOT NULL,
    TotalTexto NVARCHAR(255) NULL,
    TipoDocumento NVARCHAR(255) NOT NULL,
    OrdenCompra_Nro NVARCHAR(255) NULL,
    NotaRecepcion_Codigo NVARCHAR(255) NULL,
    Codigo_Detraccion NVARCHAR(255) NULL,
    FechaConsulta DATETIME NULL,
    DiaPago INT NOT NULL,
    FechaVencimientoPago DATETIME NULL,
    PorcentajeDetraccion DECIMAL(18, 2) NOT NULL,
    MontoDetraccion DECIMAL(18, 2) NOT NULL,
    DescripcionDetraccion NVARCHAR(255) NULL,
    EstadoSunat NVARCHAR(255) NULL,
    TipoDocumentoNeoGrid NVARCHAR(255) NULL,
    MontoOtrosCargos DECIMAL(18, 2) NOT NULL,
    CorrelativoPortal INT NULL,
    OtroCargoAplicable DECIMAL(18, 2) NOT NULL
);