
-- 
CREATE OR ALTER PROCEDURE sp_RegistrarComprobante
(

    @Id	int = null,
	@DocumentoPago_Id	int = null,
	@Nro	nvarchar(510) = null,
	@FechaEmision	datetime = null,
	@Moneda_Id	nvarchar(510) = null,
	@Proveedor_NroIdentificacion	nvarchar(510) = null,
	@Proveedor_RazonSocial	nvarchar(510) = null,
	@Cliente_NroIdentificacion	nvarchar(510) = null,
	@Cliente_RazonSocial	nvarchar(510) = null,
	@SubTotal	decimal(9,2) = null,
	@Anticipo	decimal(9,2) = null,
	@Descuento	decimal(9,2) = null,
	@OperacionGravada	decimal(9,2) = null,
	@OperacionExonerada	decimal(9,2) = null,
	@ISC	decimal(9,2) = null,
	@IVA	decimal(9,2) = null,
	@OtroCargo	decimal(9,2) = null,
	@OtroTributo	decimal(9,2) = null,
	@Total	decimal(9,2) = null,
	@OperacionGratuita	decimal(9,2) = null,
	@TotalTexto	nvarchar(510) = null,
	@TipoDocumento	nvarchar(510) = null,
	@OrdenCompra_Nro	nvarchar(510) = null,
	@NotaRecepcion_Codigo	nvarchar(510) = null,
	@Codigo_Detraccion	nvarchar(510) = null,
	@FechaConsulta	datetime = null,
	@DiaPago	int = null,
	@FechaVencimientoPago	datetime = null,
	@PorcentajeDetraccion	decimal(9,2) = null,
	@MontoDetraccion	decimal(9,2) = null,
	@DescripcionDetraccion	nvarchar(510) = null,
	@EstadoSunat	nvarchar(510) = null,
	@TipoDocumentoNeoGrid	nvarchar(510) = null,
	@MontoOtrosCargos	decimal(9,2) = null,
	@CorrelativoPortal	int = null,
	@OtroCargoAplicable	decimal(9,2) = null,
	@Creado	datetime = null
)
AS
BEGIN
	SET @Id = ISNULL(
		(SELECT
				MAX(Id)
			FROM
				Comprobante
		),
    0) + 1

    INSERT INTO Comprobante(
	Id,
	DocumentoPago_Id,
	Nro,
	FechaEmision,
	Moneda_Id,
	Proveedor_NroIdentificacion,
	Proveedor_RazonSocial,
	Cliente_NroIdentificacion,
	Cliente_RazonSocial,
	SubTotal,
	Anticipo,
	Descuento,
	OperacionGravada,
	OperacionExonerada,
	ISC,
	IVA,
	OtroCargo,
	OtroTributo,
	Total,
	OperacionGratuita,
	TotalTexto,
	TipoDocumento,
	OrdenCompra_Nro,
	NotaRecepcion_Codigo,
	Codigo_Detraccion,
	FechaConsulta,
	DiaPago,
	FechaVencimientoPago,
	PorcentajeDetraccion,
	MontoDetraccion,
	DescripcionDetraccion,
	EstadoSunat,
	TipoDocumentoNeoGrid,
	MontoOtrosCargos,
	CorrelativoPortal,
	OtroCargoAplicable,
	Creado
	)
    VALUES (
	@Id,
	@DocumentoPago_Id,
	@Nro,
	@FechaEmision,
	@Moneda_Id,
	@Proveedor_NroIdentificacion,
	@Proveedor_RazonSocial,
	@Cliente_NroIdentificacion,
	@Cliente_RazonSocial,
	@SubTotal,
	@Anticipo,
	@Descuento,
	@OperacionGravada,
	@OperacionExonerada,
	@ISC,
	@IVA,
	@OtroCargo,
	@OtroTributo,
	@Total,
	@OperacionGratuita,
	@TotalTexto,
	@TipoDocumento,
	@OrdenCompra_Nro,
	@NotaRecepcion_Codigo,
	@Codigo_Detraccion,
	@FechaConsulta,
	@DiaPago,
	@FechaVencimientoPago,
	@PorcentajeDetraccion,
	@MontoDetraccion,
	@DescripcionDetraccion,
	@EstadoSunat,
	@TipoDocumentoNeoGrid,
	@MontoOtrosCargos,
	@CorrelativoPortal,
	@OtroCargoAplicable,
	@Creado	
	);
END
GO
